connect 'jdbc:derby:data/database;create=true';

AUTOCOMMIT OFF;

-- known skype users

CREATE TABLE USERS (
    SKYPEID VARCHAR(128) NOT NULL,
    ROLE VARCHAR(16) NOT NULL
);

ALTER TABLE USERS
    ADD CONSTRAINT USERS_PK Primary Key (SKYPEID);

-- known skype chats

CREATE TABLE CHATS (
    SKYPEID VARCHAR(128) NOT NULL,
    ENABLE_RESPONSE SMALLINT NOT NULL,
    ENABLE_ONNN SMALLINT NOT NULL,
    IS_DEFAULT SMALLINT NOT NULL
);

ALTER TABLE CHATS
    ADD CONSTRAINT CHATS_PK Primary Key (SKYPEID);

-- ONNN entries

CREATE TABLE ONNNS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    VOTER VARCHAR(128) NOT NULL,
    TARGET VARCHAR(128) NOT NULL,
    CHAT VARCHAR(128) NOT NULL,
    TS TIMESTAMP NOT NULL
);

ALTER TABLE ONNNS
    ADD CONSTRAINT ONNS_PK Primary Key (ID);

ALTER TABLE ONNNS
    ADD CONSTRAINT ONNS_UNIQ Unique (VOTER, TARGET, CHAT);

ALTER TABLE ONNNS
    ADD CONSTRAINT ONNS_VOTER_FK Foreign Key (VOTER)
        REFERENCES USERS (SKYPEID);

ALTER TABLE ONNNS
    ADD CONSTRAINT ONNS_TARGET_FK Foreign Key (TARGET)
        REFERENCES USERS (SKYPEID);

ALTER TABLE ONNNS
    ADD CONSTRAINT ONNS_CHAT_FK Foreign Key (CHAT)
        REFERENCES CHATS (SKYPEID);

-- chat-related user data

CREATE TABLE PARTICIPANTS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    USR VARCHAR(128) NOT NULL,
    CHAT VARCHAR(128) NOT NULL,
    ENTERED TIMESTAMP NOT NULL
);

ALTER TABLE PARTICIPANTS
    ADD CONSTRAINT PARTICIPANTS_PK Primary Key (ID);

ALTER TABLE PARTICIPANTS
    ADD CONSTRAINT PARTICIPANTS_UNIQ Unique (USR, CHAT);

ALTER TABLE PARTICIPANTS
    ADD CONSTRAINT PARTICIPANTS_USER_FK Foreign Key (USR)
        REFERENCES USERS (SKYPEID);

ALTER TABLE PARTICIPANTS
    ADD CONSTRAINT PARTICIPANTS_CHAT_FK Foreign Key (CHAT)
        REFERENCES CHATS (SKYPEID);

-- chat stats

CREATE TABLE STATS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    USR VARCHAR(128) NOT NULL,
    CHAT VARCHAR(128) NOT NULL,
    STARTED TIMESTAMP NOT NULL,
    UPDATED TIMESTAMP NOT NULL,
    MESSAGES BIGINT NOT NULL,
    WORDS BIGINT NOT NULL,
    SYMBOLS BIGINT NOT NULL,
    COMMANDS BIGINT NOT NULL,
    TOPICS BIGINT NOT NULL
);


ALTER TABLE STATS
    ADD CONSTRAINT STATS_PK Primary Key (ID);

ALTER TABLE STATS
    ADD CONSTRAINT STATS_UNIQ Unique (USR, CHAT);

ALTER TABLE STATS
    ADD CONSTRAINT STATS_USER_FK Foreign Key (USR)
        REFERENCES USERS (SKYPEID);

ALTER TABLE STATS
    ADD CONSTRAINT STATS_CHAT_FK Foreign Key (CHAT)
        REFERENCES CHATS (SKYPEID);


COMMIT;

exit;