connect 'jdbc:derby:data/database;create=false';

AUTOCOMMIT OFF;

ALTER TABLE CHATS
    ADD SILENT_FACTOR INTEGER NOT NULL DEFAULT 1;

ALTER TABLE CHATS
    ADD EXITCOST INTEGER NOT NULL DEFAULT 0;


ALTER TABLE PARTICIPANTS
    ADD DEBT BIGINT DEFAULT 0;

CREATE TABLE FEEDS(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    URL VARCHAR(256) NOT NULL,
    CHAT VARCHAR(128) NOT NULL,
    USR VARCHAR(128) NOT NULL,
    FETCH_INTERVAL INTEGER NOT NULL DEFAULT 1800,
    SHOW_INTERVAL INTEGER NOT NULL DEFAULT 0,
    LAST_FETCHED TIMESTAMP NOT NULL
);

ALTER TABLE FEEDS
    ADD CONSTRAINT FEED_CHAT_FK Foreign Key (CHAT)
        REFERENCES CHATS (SKYPEID);

ALTER TABLE FEEDS
    ADD CONSTRAINT FEED_CHAT_FK Foreign Key (USR)
        REFERENCES USERS (SKYPEID);

ALTER TABLE FEEDS
    ADD CONSTRAINT FEEDS_UNIQ Unique (URL, CHAT);




COMMIT;

exit;